import type { Metadata } from "next"
import { DetailedServiceTemplate } from "@/components/services/enterprise/detailed-service-template"
import { Shield, Lock, Eye, AlertTriangle, Users, FileText } from "lucide-react"

export const metadata: Metadata = {
  title: "Cybersecurity - F09 Tech",
  description:
    "Enterprise-grade security solutions including threat detection, prevention, compliance management, and security audits.",
}

export default function CybersecurityPage() {
  return (
    <main className="flex min-h-screen flex-col">
      <DetailedServiceTemplate
        title="Cybersecurity"
        description="Enterprise-grade security solutions including threat detection, prevention, compliance management, and security audits."
        category="Security Solutions"
        icon={<Shield className="h-6 w-6" />}
        features={[
          {
            title: "Vulnerability Assessment",
            description:
              "Comprehensive scanning and assessment to identify security weaknesses in your systems and applications.",
          },
          {
            title: "Penetration Testing",
            description:
              "Simulated cyber attacks to evaluate the security of your systems and identify exploitable vulnerabilities.",
          },
          {
            title: "Security Information & Event Management (SIEM)",
            description: "Real-time analysis of security alerts generated by applications and network hardware.",
          },
          {
            title: "Zero Trust Architecture",
            description:
              "Implementation of security models that require strict identity verification for every person and device.",
          },
          {
            title: "Endpoint Detection & Response",
            description:
              "Advanced protection for endpoints against threats like malware, ransomware, and zero-day exploits.",
          },
          {
            title: "Security Awareness Training",
            description:
              "Comprehensive training programs to educate employees about security risks and best practices.",
          },
        ]}
        benefits={[
          {
            title: "Reduced Risk of Data Breaches",
            description:
              "Minimize the likelihood of successful cyber attacks and data breaches through proactive security measures.",
          },
          {
            title: "Regulatory Compliance",
            description:
              "Meet industry-specific compliance requirements and avoid costly penalties for non-compliance.",
          },
          {
            title: "Business Continuity",
            description:
              "Maintain operations during and after security incidents with effective incident response and recovery plans.",
          },
          {
            title: "Customer Trust",
            description:
              "Build and maintain customer trust by demonstrating commitment to protecting their sensitive information.",
          },
          {
            title: "Competitive Advantage",
            description:
              "Differentiate your business by making security a priority in an increasingly threat-conscious market.",
          },
          {
            title: "Cost Savings",
            description:
              "Reduce the financial impact of security incidents, which can include remediation costs, legal fees, and reputation damage.",
          },
        ]}
        implementation={[
          {
            title: "Security Assessment",
            description:
              "Evaluate current security posture, identify gaps, and develop a comprehensive security strategy.",
          },
          {
            title: "Security Architecture Design",
            description:
              "Design a multi-layered security architecture tailored to your organization's specific needs and risk profile.",
          },
          {
            title: "Security Controls Implementation",
            description:
              "Deploy and configure security technologies and controls according to industry best practices.",
          },
          {
            title: "Security Monitoring Setup",
            description:
              "Implement continuous monitoring solutions to detect and alert on suspicious activities and potential threats.",
          },
          {
            title: "Incident Response Planning",
            description:
              "Develop and test incident response procedures to ensure rapid and effective handling of security incidents.",
          },
          {
            title: "Ongoing Management & Optimization",
            description:
              "Continuously evaluate and improve security measures to address evolving threats and business needs.",
          },
        ]}
        technologies={[
          {
            name: "Next-Gen Firewalls",
            description:
              "Advanced network security devices that provide deep packet inspection and application-level filtering.",
            icon: <Shield className="h-6 w-6" />,
          },
          {
            name: "Endpoint Protection Platforms",
            description: "Comprehensive security solutions for detecting and blocking threats on endpoint devices.",
            icon: <Lock className="h-6 w-6" />,
          },
          {
            name: "SIEM Solutions",
            description:
              "Platforms that collect, analyze, and correlate security event data from across your organization.",
            icon: <Eye className="h-6 w-6" />,
          },
          {
            name: "Threat Intelligence Platforms",
            description: "Services that provide actionable information about emerging threats and vulnerabilities.",
            icon: <AlertTriangle className="h-6 w-6" />,
          },
          {
            name: "Identity & Access Management",
            description:
              "Solutions for managing user identities and controlling access to resources based on roles and policies.",
            icon: <Users className="h-6 w-6" />,
          },
          {
            name: "Governance, Risk & Compliance",
            description: "Tools for managing security policies, assessing risks, and ensuring regulatory compliance.",
            icon: <FileText className="h-6 w-6" />,
          },
        ]}
        useCases={[
          "Protection of sensitive customer data and intellectual property",
          "Securing remote work environments and distributed workforces",
          "Defending against advanced persistent threats targeting your industry",
          "Meeting compliance requirements for regulated industries (healthcare, finance, etc.)",
          "Securing cloud-based applications and infrastructure",
          "Protecting operational technology and industrial control systems",
        ]}
      />
    </main>
  )
}
